/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "../types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface NameClashes extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): NameClashes;
  clone(): NameClashes;
  methods: {
    attach(): NonPayableTransactionObject<string>;

    connect(): NonPayableTransactionObject<string>;

    deployed(): NonPayableTransactionObject<string>;

    filters(): NonPayableTransactionObject<string>;

    getAddress(): NonPayableTransactionObject<string>;

    getDeployedCode(): NonPayableTransactionObject<string>;

    getFunction(): NonPayableTransactionObject<string>;

    listeners(): NonPayableTransactionObject<string>;

    off(): NonPayableTransactionObject<string>;

    on(): NonPayableTransactionObject<string>;

    once(): NonPayableTransactionObject<string>;

    provider(): NonPayableTransactionObject<string>;

    runner(): NonPayableTransactionObject<string>;

    signer(): NonPayableTransactionObject<string>;

    target(): NonPayableTransactionObject<string>;

    then(): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
